# Stage 1: Build the Angular application
FROM node:22.0.0 as build

WORKDIR /app/client

COPY package*.json ./
RUN npm install

COPY . .

RUN ls -l /app/client # Debug step to list contents
RUN npm run build:ssr

# Stage 2: Serve the Angular application
FROM node:22.0.0

WORKDIR /app/client

COPY --from=build /app/client/dist /app/client/dist

RUN ls -l /app/client/dist # Debug step to list contents

EXPOSE 4000

CMD ["npm", "run", "serve:ssr:client"]