services:
  django:
    build:
      context: ./commerce
      dockerfile: ../Dockerfile.django
    volumes:
      - ./commerce:/app
    environment:
      DJANGO_SETTINGS_MODULE: settings.production
    ports:
      - "8000:8000"
    depends_on:
      - db

  angular:
    build:
      context: ./client
      dockerfile: ../Dockerfile.angular
    volumes:
      - ./client:/app
    ports:
      - "4300:80"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - angular
      - django

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data: