version: '3'

services:
  django:
    build:
      context: ./commerce
      dockerfile: ../Dockerfile.django
    volumes:
      - ./commerce:/app:delegated
      - ./commerce/staticfiles:/app/staticfiles
    command: gunicorn --bind 0.0.0.0:8001 commerce.wsgi:application
    environment:
      DJANGO_SETTINGS_MODULE: commerce.settings.production
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
    ports:
      - "8001:8001"
    depends_on:
      - db
      - redis

  redis:
    image: redis:latest
    ports:
      - '6379:6379'

  angular:
    build:
      context: ./client
      dockerfile: ../Dockerfile.angular
    volumes:
      - ./client:/app:delegated
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
    command: npm run serve:ssr
    depends_on:
      - django

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data: