# Dockerfile for Django
FROM python:3.10

ENV PYTHONUNBUFFERED 1

WORKDIR /app

# Install necessary system libraries
RUN apt-get update && apt-get install -y \
    libsystemd-dev

# Copy requirements.txt from the context directory (commerce)
COPY requirements.txt /app/

RUN pip install -r requirements.txt

COPY . /app/

CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]