services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  django:
    build:
      context: ./commerce
      dockerfile: ../Dockerfile.django
    volumes:
      - ./commerce:/app:delegated
      - ./static:/app/staticfiles
      - ./media:/app/media
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DJANGO_SETTINGS_MODULE: ${DJANGO_SETTINGS_MODULE}
    depends_on:
      - db
      - redis
    ports:
      - '8003:8000'  # Changed to map Django's internal port to 8003 on the host

  redis:
    image: redis:latest
    ports:
      - '6379:6379'

volumes:
  postgres_data:
  static:
  media: