services:
  django:
    build:
      context: ./commerce
      dockerfile: ../Dockerfile.django
    volumes:
      - ./commerce:/app:delegated
    environment:
      DJANGO_SETTINGS_MODULE: commerce.settings.development
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
    ports:
      - "8001:8000"
    depends_on:
      - db

  angular:
    build:
      context: ./client
      dockerfile: ../Dockerfile.angular
    volumes:
      - ./client:/app:delegated
    ports:
      - "4200:4200"
    environment:
      - CHOKIDAR_USEPOLLING=true

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data: