services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  
  django:
    build:
      context: ./commerce
      dockerfile: ../Dockerfile.django
    volumes:
      - ./commerce:/app:delegated
      - ./commerce/staticfiles:/app/staticfiles
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DJANGO_SETTINGS_MODULE: ${DJANGO_SETTINGS_MODULE}
    depends_on:
      - db
      - redis
    ports:
      - '8003:8003'

  redis:
    image: redis:latest
    ports:
      - '6379:6379'

  angular:
    build:
      context: ./client
      dockerfile: ../Dockerfile.angular
    volumes:
      - ./client:/app:delegated
    command: npm run serve:ssr
    depends_on:
      - django

  # nginx:
  #   image: nginx:latest
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  #   ports:
  #     - "80:80"
  #   links:
  #     - db
  #   depends_on:
  #     - django
  #     - angular

volumes:
  postgres_data: