services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - django
      - angular

  django:
    build:
      context: ./commerce
      dockerfile: Dockerfile.django
    command: daphne -b 0.0.0.0 -p 8000 commerce.asgi:application
    volumes:
      - ./commerce:/srv/www/friendsdiscount/django
      - ./static:/srv/www/friendsdiscount/django/static
    expose:
      - 8000
    env_file:
      - ./.env
    depends_on:
      - db
      - redis

  angular:
    build:
      context: ./client
      dockerfile: Dockerfile.angular
    command: node dist/client/server/server.mjs
    ports:
      - "4000:4000"
    environment:
      NODE_ENV: production

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  redis:
    image: redis:6
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
