services:
  django:
    build:
      context: ./commerce
      dockerfile: ../Dockerfile.django
    volumes:
      - ./commerce:/app:delegated
      - ./commerce/staticfiles:/app/staticfiles
    command: daphne -b 0.0.0.0 -p 8000 commerce.asgi:application
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DJANGO_SETTINGS_MODULE: ${DJANGO_SETTINGS_MODULE}
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  redis:
    image: redis:latest
    ports:
      - '6379:6379'

  angular:
    build:
      context: ./client
      dockerfile: ../Dockerfile.angular
    volumes:
      - ./client:/app:delegated
    ports:
      - "4200:4200"
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - django

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: matt@harris.pro
      PGADMIN_DEFAULT_PASSWORD: 1234
      PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION: 'False'
    ports:
      - "5050:80"
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data: