# Use the latest Node.js LTS version
FROM node:18-alpine as build

WORKDIR /app

# Install Angular CLI globally
RUN npm install -g @angular/cli

# Install dependencies
COPY package.json package-lock.json ./
RUN npm install

RUN ng build --configuration production

# Copy the project files
COPY . .

# Expose the Angular development server
# CMD ["ng", "run", "build", "configuration", "production"]