# Generated by Django 3.2.25 on 2024-06-18 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20240618_0507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='email_address',
        ),
        migrations.RemoveField(
            model_name='message',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='message',
            name='title',
        ),
        migrations.AddField(
            model_name='conversation',
            name='email_address',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
